apiVersion: v1
kind: Service
metadata:
  name: cubix-service-frontapp
  labels:
    training: block3
    homework: frontapp
spec:
  selector:
    homework: frontapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080