apiVersion: v1
kind: Service
metadata:
  name: cubix-service-backapp
  labels:
    training: block3
    homework: backapp
spec:
  selector:
    homework: backapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080